/*
 * main.h
 *
 *  Created on: Jan 6, 2015
 *      Author: bohni
 */

#ifndef MAIN_H_
#define MAIN_H_


/* autogenerated includes  -----------------------------------------*/
#include "stm32f3xx_hal.h"
#include "stm32f3xx_it.h"
#include "diag/Trace.h"
#include "i2c.h"
#include "dma.h"
#include "tim.h"
#include "gpio.h"
#include "adc.h"


/* classes  ---------------------------------------------------------*/
#include "config.h"
#include "ConfigReader.h"
#include "Scheduler.h"
#include "Task.h"
#include "LedBlink.h"
#include "RCreceiver.h"
#include "PPMGenerator.h"
#include "ComplementaryFilter.h"
#include "Compass.h"
#include "PIDController.h"
#include "MPU9150.h"
#include "usbhandler.h"
#include "AkkuMonitor.h"
#include "BMP180.h"
#include "DiscoveryLEDs.h"


/* Private variables ---------------------------------------------------------*/

extern Status status;
extern ConfigReader configReader;
extern Scheduler scheduler;
extern RCreceiver rcReceiver;
extern MPU9150 mpu9150;
extern PIDController pidControllerX;
extern PIDController pidControllerY;
extern AkkuMonitor akku;
extern BMP180 baro;

/* onboard leds*/
typedef struct {
    LedBlink* led3;
    LedBlink* led4;
    LedBlink* led5;
    LedBlink* led6;
    LedBlink* led7;
    LedBlink* led8;
    LedBlink* led9;
    LedBlink* led10;

}OnBoardLEDs;
extern OnBoardLEDs leds;

extern DiscoveryLEDs led;
#endif /* MAIN_H_ */
